openapi: 3.1.0
info:
  title: IDAP 进销存业务系统 API
  version: 0.1.0
  description: |
    v1 REST 接口契约（多租户、JWT）。
    - 全局必需请求头：`X-Tenant-Id`, `X-Correlation-Id`
    - 安全：HTTP Bearer JWT
servers:
  - url: /api/v1
security:
  - bearerAuth: []
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  parameters:
    XTenantId:
      name: X-Tenant-Id
      in: header
      required: true
      schema:
        type: string
    XCorrelationId:
      name: X-Correlation-Id
      in: header
      required: true
      schema:
        type: string
        minLength: 8
  schemas:
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          example: 200
        msg:
          type: string
          example: success
        data: {}
    PageResult:
      type: object
      properties:
        items:
          type: array
          items: {}
        total:
          type: integer
      required: [items, total]
    Product:
      $ref: ./schemas/domain/product.json
    Warehouse:
      $ref: ./schemas/domain/warehouse.json
    Supplier:
      $ref: ./schemas/domain/supplier.json
    Customer:
      $ref: ./schemas/domain/customer.json
    PurchaseOrder:
      $ref: ./schemas/domain/purchase-order.json
    SalesOrder:
      $ref: ./schemas/domain/sales-order.json
    Inventory:
      $ref: ./schemas/domain/inventory.json
    StockMovement:
      $ref: ./schemas/domain/stock-movement.json
paths:
  /products:
    get:
      tags: [MasterData]
      summary: 列出商品
      parameters:
        - $ref: "#/components/parameters/XTenantId"
        - $ref: "#/components/parameters/XCorrelationId"
        - in: query
          name: page
          schema: { type: integer, minimum: 1, default: 1 }
        - in: query
          name: size
          schema: { type: integer, minimum: 1, maximum: 200, default: 20 }
        - in: query
          name: keyword
          schema: { type: string }
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/ApiResponse"
                  - type: object
                    properties:
                      data:
                        $ref: "#/components/schemas/PageResult"
    post:
      tags: [MasterData]
      summary: 新建商品
      parameters:
        - $ref: "#/components/parameters/XTenantId"
        - $ref: "#/components/parameters/XCorrelationId"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/ApiResponse"
                  - type: object
                    properties:
                      data:
                        $ref: "#/components/schemas/Product"
  /products/{id}:
    get:
      tags: [MasterData]
      summary: 获取商品
      parameters:
        - $ref: "#/components/parameters/XTenantId"
        - $ref: "#/components/parameters/XCorrelationId"
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/ApiResponse"
                  - type: object
                    properties:
                      data:
                        $ref: "#/components/schemas/Product"
    put:
      tags: [MasterData]
      summary: 更新商品
      parameters:
        - $ref: "#/components/parameters/XTenantId"
        - $ref: "#/components/parameters/XCorrelationId"
        - in: path
          name: id
          required: true
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponse"
    delete:
      tags: [MasterData]
      summary: 删除商品
      parameters:
        - $ref: "#/components/parameters/XTenantId"
        - $ref: "#/components/parameters/XCorrelationId"
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponse"
  /warehouses:
    get:
      tags: [MasterData]
      summary: 列出仓库
      parameters:
        - $ref: "#/components/parameters/XTenantId"
        - $ref: "#/components/parameters/XCorrelationId"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/ApiResponse"
                  - type: object
                    properties:
                      data:
                        $ref: "#/components/schemas/PageResult"
    post:
      tags: [MasterData]
      summary: 新建仓库
      parameters:
        - $ref: "#/components/parameters/XTenantId"
        - $ref: "#/components/parameters/XCorrelationId"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Warehouse"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponse"
  /suppliers:
    get:
      tags: [MasterData]
      summary: 列出供应商
      parameters:
        - $ref: "#/components/parameters/XTenantId"
        - $ref: "#/components/parameters/XCorrelationId"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/ApiResponse"
                  - type: object
                    properties:
                      data:
                        $ref: "#/components/schemas/PageResult"
    post:
      tags: [MasterData]
      summary: 新建供应商
      parameters:
        - $ref: "#/components/parameters/XTenantId"
        - $ref: "#/components/parameters/XCorrelationId"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Supplier"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponse"
  /customers:
    get:
      tags: [MasterData]
      summary: 列出客户
      parameters:
        - $ref: "#/components/parameters/XTenantId"
        - $ref: "#/components/parameters/XCorrelationId"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/ApiResponse"
                  - type: object
                    properties:
                      data:
                        $ref: "#/components/schemas/PageResult"
    post:
      tags: [MasterData]
      summary: 新建客户
      parameters:
        - $ref: "#/components/parameters/XTenantId"
        - $ref: "#/components/parameters/XCorrelationId"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Customer"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponse"
  /purchase-orders:
    get:
      tags: [Purchase]
      summary: 列出采购单
      parameters:
        - $ref: "#/components/parameters/XTenantId"
        - $ref: "#/components/parameters/XCorrelationId"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/ApiResponse"
                  - type: object
                    properties:
                      data:
                        $ref: "#/components/schemas/PageResult"
    post:
      tags: [Purchase]
      summary: 新建采购单
      parameters:
        - $ref: "#/components/parameters/XTenantId"
        - $ref: "#/components/parameters/XCorrelationId"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PurchaseOrder"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/ApiResponse"
                  - type: object
                    properties:
                      data:
                        $ref: "#/components/schemas/PurchaseOrder"
  /purchase-orders/{id}:
    get:
      tags: [Purchase]
      summary: 获取采购单
      parameters:
        - $ref: "#/components/parameters/XTenantId"
        - $ref: "#/components/parameters/XCorrelationId"
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/ApiResponse"
                  - type: object
                    properties:
                      data:
                        $ref: "#/components/schemas/PurchaseOrder"
    put:
      tags: [Purchase]
      summary: 更新采购单
      parameters:
        - $ref: "#/components/parameters/XTenantId"
        - $ref: "#/components/parameters/XCorrelationId"
        - in: path
          name: id
          required: true
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PurchaseOrder"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponse"
  /purchase-orders/{id}/submit:
    post:
      tags: [Purchase]
      summary: 提交采购单
      parameters:
        - $ref: "#/components/parameters/XTenantId"
        - $ref: "#/components/parameters/XCorrelationId"
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponse"
  /purchase-orders/{id}/approve:
    post:
      tags: [Purchase]
      summary: 审批采购单
      parameters:
        - $ref: "#/components/parameters/XTenantId"
        - $ref: "#/components/parameters/XCorrelationId"
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        "200": { description: OK }
  /purchase-orders/{id}/receive:
    post:
      tags: [Purchase]
      summary: 到货入库
      parameters:
        - $ref: "#/components/parameters/XTenantId"
        - $ref: "#/components/parameters/XCorrelationId"
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        "200": { description: OK }
  /sales-orders:
    get:
      tags: [Sales]
      summary: 列出销售单
      parameters:
        - $ref: "#/components/parameters/XTenantId"
        - $ref: "#/components/parameters/XCorrelationId"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/ApiResponse"
                  - type: object
                    properties:
                      data:
                        $ref: "#/components/schemas/PageResult"
    post:
      tags: [Sales]
      summary: 新建销售单
      parameters:
        - $ref: "#/components/parameters/XTenantId"
        - $ref: "#/components/parameters/XCorrelationId"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SalesOrder"
      responses:
        "200": { description: OK }
  /sales-orders/{id}/confirm:
    post:
      tags: [Sales]
      summary: 确认销售单
      parameters:
        - $ref: "#/components/parameters/XTenantId"
        - $ref: "#/components/parameters/XCorrelationId"
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        "200": { description: OK }
  /sales-orders/{id}/allocate:
    post:
      tags: [Sales]
      summary: 分配库存
      parameters:
        - $ref: "#/components/parameters/XTenantId"
        - $ref: "#/components/parameters/XCorrelationId"
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        "200": { description: OK }
  /sales-orders/{id}/ship:
    post:
      tags: [Sales]
      summary: 出库发货
      parameters:
        - $ref: "#/components/parameters/XTenantId"
        - $ref: "#/components/parameters/XCorrelationId"
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        "200": { description: OK }
  /inventory:
    get:
      tags: [Inventory]
      summary: 查询库存
      parameters:
        - $ref: "#/components/parameters/XTenantId"
        - $ref: "#/components/parameters/XCorrelationId"
        - in: query
          name: productId
          schema: { type: string }
        - in: query
          name: warehouseId
          schema: { type: string }
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/ApiResponse"
                  - type: object
                    properties:
                      data:
                        type: array
                        items:
                          $ref: "#/components/schemas/Inventory"
  /stock-movements:
    get:
      tags: [Inventory]
      summary: 库存流水
      parameters:
        - $ref: "#/components/parameters/XTenantId"
        - $ref: "#/components/parameters/XCorrelationId"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/ApiResponse"
                  - type: object
                    properties:
                      data:
                        $ref: "#/components/schemas/PageResult"
    post:
      tags: [Inventory]
      summary: 记一笔出入库/调整
      parameters:
        - $ref: "#/components/parameters/XTenantId"
        - $ref: "#/components/parameters/XCorrelationId"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/StockMovement"
      responses:
        "200": { description: OK }
